server:
  port: 8848
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: CONFIG_SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cby0123/aigou_config.git  #git文件地址
          username: cby0123
          password: qwedc0123